"""Remove strategy and trading_enabled columns from Settings

Revision ID: 11536abfa0fe
Revises: 6e84910cc7f7
Create Date: 2024-10-01 21:23:13.683908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11536abfa0fe'
down_revision = '6e84910cc7f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_column('trading_enabled')
        batch_op.drop_column('strategy')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('strategy', sa.VARCHAR(length=16), nullable=True))
        batch_op.add_column(sa.Column('trading_enabled', sa.VARCHAR(length=16), nullable=True))

    # ### end Alembic commands ###
