"""empty message

Revision ID: 18f1c4dea986
Revises: 741ea421dc9b
Create Date: 2024-10-18 20:28:34.751502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18f1c4dea986'
down_revision = '741ea421dc9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot_settings', schema=None) as batch_op:
        batch_op.alter_column('algorithm',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=16),
               existing_nullable=True)

    with op.batch_alter_table('trades_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('algorithm', sa.String(length=16), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trades_history', schema=None) as batch_op:
        batch_op.drop_column('algorithm')

    with op.batch_alter_table('bot_settings', schema=None) as batch_op:
        batch_op.alter_column('algorithm',
               existing_type=sa.String(length=16),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
