"""empty message

Revision ID: 1fffff2be8d2
Revises: 39691c9a8487
Create Date: 2024-11-03 12:05:03.063627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fffff2be8d2'
down_revision = '39691c9a8487'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtest_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.String(length=16), nullable=True),
    sa.Column('end_date', sa.String(length=16), nullable=True),
    sa.Column('initial_balance', sa.Float(), nullable=True),
    sa.Column('final_balance', sa.Float(), nullable=True),
    sa.Column('profit', sa.Float(), nullable=True),
    sa.Column('trade_log', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('backtest_results')
    # ### end Alembic commands ###
