"""empty message

Revision ID: 201151556ae3
Revises: e55336c4e37f
Create Date: 2024-10-16 22:54:49.426636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '201151556ae3'
down_revision = 'e55336c4e37f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot_current_trade', schema=None) as batch_op:
        batch_op.drop_column('type')

    with op.batch_alter_table('trades_history', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trades_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.VARCHAR(length=16), nullable=True))

    with op.batch_alter_table('bot_current_trade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.VARCHAR(length=16), nullable=True))

    # ### end Alembic commands ###
