"""empty message

Revision ID: 264a98a63a96
Revises: 8501d34c5d83
Create Date: 2024-11-17 21:49:25.930845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '264a98a63a96'
down_revision = '8501d34c5d83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot_settings', schema=None) as batch_op:
        batch_op.alter_column('macd_timeperiod',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('macd_signalperiod',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('boilinger_timeperiod',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('boilinger_nbdev',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('stock_k_timeperiod',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('stock_d_timeperiod',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('ema_fast_timeperiod',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('ema_slow_timeperiod',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot_settings', schema=None) as batch_op:
        batch_op.alter_column('ema_slow_timeperiod',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('ema_fast_timeperiod',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('stock_d_timeperiod',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('stock_k_timeperiod',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('boilinger_nbdev',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('boilinger_timeperiod',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('macd_signalperiod',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('macd_timeperiod',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
