"""empty message

Revision ID: 2b26bb8eb8d1
Revises: 936c4ca07b5b
Create Date: 2024-11-03 20:44:08.442245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b26bb8eb8d1'
down_revision = '936c4ca07b5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sell_signal_only_trailing_stop', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('atr_trailing_stop', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot_settings', schema=None) as batch_op:
        batch_op.drop_column('atr_trailing_stop')
        batch_op.drop_column('sell_signal_only_trailing_stop')

    # ### end Alembic commands ###
