"""empty message

Revision ID: 338d4377e16c
Revises: 
Create Date: 2024-11-22 21:31:07.548028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '338d4377e16c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtest_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(length=16), nullable=True),
    sa.Column('strategy', sa.String(length=16), nullable=True),
    sa.Column('algorithm', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.String(length=16), nullable=True),
    sa.Column('end_date', sa.String(length=16), nullable=True),
    sa.Column('initial_balance', sa.Float(), nullable=True),
    sa.Column('final_balance', sa.Float(), nullable=True),
    sa.Column('profit', sa.Float(), nullable=True),
    sa.Column('trade_log', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('backtest_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.String(length=16), nullable=False),
    sa.Column('end_date', sa.String(length=16), nullable=False),
    sa.Column('csv_file_path', sa.String(length=64), nullable=False),
    sa.Column('initial_balance', sa.Float(), nullable=False),
    sa.Column('crypto_balance', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bot_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('strategy', sa.String(length=16), nullable=False),
    sa.Column('algorithm', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=1024), nullable=True),
    sa.Column('trailing_stop_pct', sa.Float(), nullable=False),
    sa.Column('sell_signal_only_trailing_stop', sa.Boolean(), nullable=False),
    sa.Column('trailing_stop_with_atr', sa.Boolean(), nullable=False),
    sa.Column('trailing_stop_atr_calc', sa.Float(), nullable=False),
    sa.Column('cci_buy', sa.Integer(), nullable=False),
    sa.Column('cci_sell', sa.Integer(), nullable=False),
    sa.Column('rsi_buy', sa.Integer(), nullable=False),
    sa.Column('rsi_sell', sa.Integer(), nullable=False),
    sa.Column('mfi_buy', sa.Integer(), nullable=False),
    sa.Column('mfi_sell', sa.Integer(), nullable=False),
    sa.Column('stoch_buy', sa.Integer(), nullable=False),
    sa.Column('stoch_sell', sa.Integer(), nullable=False),
    sa.Column('timeperiod', sa.Integer(), nullable=False),
    sa.Column('rsi_timeperiod', sa.Integer(), nullable=False),
    sa.Column('atr_timeperiod', sa.Integer(), nullable=False),
    sa.Column('cci_timeperiod', sa.Integer(), nullable=False),
    sa.Column('mfi_timeperiod', sa.Integer(), nullable=False),
    sa.Column('macd_timeperiod', sa.Integer(), nullable=False),
    sa.Column('macd_signalperiod', sa.Integer(), nullable=False),
    sa.Column('boilinger_timeperiod', sa.Integer(), nullable=False),
    sa.Column('boilinger_nbdev', sa.Integer(), nullable=False),
    sa.Column('stock_k_timeperiod', sa.Integer(), nullable=False),
    sa.Column('stock_d_timeperiod', sa.Integer(), nullable=False),
    sa.Column('ema_fast_timeperiod', sa.Integer(), nullable=False),
    sa.Column('ema_slow_timeperiod', sa.Integer(), nullable=False),
    sa.Column('psar_acceleration', sa.Float(), nullable=False),
    sa.Column('psar_maximum', sa.Float(), nullable=False),
    sa.Column('interval', sa.String(length=16), nullable=False),
    sa.Column('lookback_period', sa.String(length=16), nullable=False),
    sa.Column('bot_running', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=56), nullable=False),
    sa.Column('name', sa.String(length=56), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('comment', sa.String(length=1024), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=False),
    sa.Column('control_panel_access', sa.Boolean(), nullable=False),
    sa.Column('admin_panel_access', sa.Boolean(), nullable=False),
    sa.Column('email_raports_receiver', sa.Boolean(), nullable=False),
    sa.Column('login_errors', sa.Integer(), nullable=False),
    sa.Column('account_suspended', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('login')
    )
    op.create_table('bot_current_trade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('buy_price', sa.Float(), nullable=True),
    sa.Column('current_price', sa.Float(), nullable=True),
    sa.Column('previous_price', sa.Float(), nullable=True),
    sa.Column('trailing_stop_loss', sa.Float(), nullable=True),
    sa.Column('price_rises_counter', sa.Integer(), nullable=True),
    sa.Column('buy_timestamp', sa.DateTime(), nullable=True),
    sa.Column('bot_settings_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bot_settings_id'], ['bot_settings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trades_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=True),
    sa.Column('strategy', sa.String(length=16), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('buy_price', sa.Float(), nullable=True),
    sa.Column('sell_price', sa.Float(), nullable=True),
    sa.Column('stablecoin_balance', sa.Float(), nullable=True),
    sa.Column('price_rises_counter', sa.Integer(), nullable=True),
    sa.Column('buy_timestamp', sa.DateTime(), nullable=True),
    sa.Column('sell_timestamp', sa.DateTime(), nullable=True),
    sa.Column('bot_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['bot_settings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trades_history')
    op.drop_table('bot_current_trade')
    op.drop_table('users')
    op.drop_table('bot_settings')
    op.drop_table('backtest_settings')
    op.drop_table('backtest_results')
    # ### end Alembic commands ###
