"""empty message

Revision ID: 413e6a045163
Revises: 673cb3589657
Create Date: 2024-10-10 19:56:20.759284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '413e6a045163'
down_revision = '673cb3589657'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('current_trade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('previous_price', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('current_trade', schema=None) as batch_op:
        batch_op.drop_column('previous_price')

    # ### end Alembic commands ###
