"""empty message

Revision ID: 4cf3b066e100
Revises: e602fbfeab60
Create Date: 2024-10-15 01:17:25.880858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cf3b066e100'
down_revision = 'e602fbfeab60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trades_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('symbol', sa.String(length=16), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trades_history', schema=None) as batch_op:
        batch_op.drop_column('symbol')

    # ### end Alembic commands ###
