"""empty message

Revision ID: 4ef9e263ab83
Revises: d8f8789b3086
Create Date: 2024-09-30 22:33:09.075607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ef9e263ab83'
down_revision = 'd8f8789b3086'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('symbol', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('stop_loss_pct', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('trailing_stop_pct', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('take_profit_pct', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('lookback_days', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('bot_running', sa.Boolean(), nullable=True))
        batch_op.drop_column('strategy')
        batch_op.drop_column('trading_enabled')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trading_enabled', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('strategy', sa.VARCHAR(length=150), nullable=True))
        batch_op.drop_column('bot_running')
        batch_op.drop_column('lookback_days')
        batch_op.drop_column('take_profit_pct')
        batch_op.drop_column('trailing_stop_pct')
        batch_op.drop_column('stop_loss_pct')
        batch_op.drop_column('symbol')

    # ### end Alembic commands ###
