"""empty message

Revision ID: 5786b2e6827f
Revises: 1bbe330e4b32
Create Date: 2024-11-12 20:03:03.233106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5786b2e6827f'
down_revision = '1bbe330e4b32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot_current_trade', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=8),
               existing_nullable=True)
        batch_op.alter_column('buy_price',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=8),
               existing_nullable=True)
        batch_op.alter_column('current_price',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=8),
               existing_nullable=True)
        batch_op.alter_column('previous_price',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=8),
               existing_nullable=True)
        batch_op.alter_column('trailing_stop_loss',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=8),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot_current_trade', schema=None) as batch_op:
        batch_op.alter_column('trailing_stop_loss',
               existing_type=sa.Numeric(precision=10, scale=8),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('previous_price',
               existing_type=sa.Numeric(precision=10, scale=8),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('current_price',
               existing_type=sa.Numeric(precision=10, scale=8),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('buy_price',
               existing_type=sa.Numeric(precision=10, scale=8),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('amount',
               existing_type=sa.Numeric(precision=10, scale=8),
               type_=sa.FLOAT(),
               existing_nullable=True)

    # ### end Alembic commands ###
