"""empty message

Revision ID: 6173c3355ec5
Revises: 5786b2e6827f
Create Date: 2024-11-13 00:33:24.601561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6173c3355ec5'
down_revision = '5786b2e6827f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot_current_trade', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.NUMERIC(precision=10, scale=8),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('buy_price',
               existing_type=sa.NUMERIC(precision=10, scale=8),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('current_price',
               existing_type=sa.NUMERIC(precision=10, scale=8),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('previous_price',
               existing_type=sa.NUMERIC(precision=10, scale=8),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('trailing_stop_loss',
               existing_type=sa.NUMERIC(precision=10, scale=8),
               type_=sa.Float(),
               existing_nullable=True)

    with op.batch_alter_table('trades_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stablecoin_balance', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trades_history', schema=None) as batch_op:
        batch_op.drop_column('stablecoin_balance')

    with op.batch_alter_table('bot_current_trade', schema=None) as batch_op:
        batch_op.alter_column('trailing_stop_loss',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=8),
               existing_nullable=True)
        batch_op.alter_column('previous_price',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=8),
               existing_nullable=True)
        batch_op.alter_column('current_price',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=8),
               existing_nullable=True)
        batch_op.alter_column('buy_price',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=8),
               existing_nullable=True)
        batch_op.alter_column('amount',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=8),
               existing_nullable=True)

    # ### end Alembic commands ###
