"""empty message

Revision ID: 673cb3589657
Revises: 325b7c903a13
Create Date: 2024-10-09 20:18:53.198980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '673cb3589657'
down_revision = '325b7c903a13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('current_trade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('trailing_stop_loss', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trades_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interval', sa.String(length=16), nullable=True))
        batch_op.drop_column('take_profit_pct')
        batch_op.drop_column('stop_loss_pct')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stop_loss_pct', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('take_profit_pct', sa.FLOAT(), nullable=True))
        batch_op.drop_column('interval')

    op.drop_table('trades_history')
    op.drop_table('current_trade')
    # ### end Alembic commands ###
