"""empty message

Revision ID: 6e84910cc7f7
Revises: 8e335d6f8b36
Create Date: 2024-10-01 20:54:53.731864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e84910cc7f7'
down_revision = '8e335d6f8b36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trading_enabled', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('strategy', sa.String(length=16), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_column('strategy')
        batch_op.drop_column('trading_enabled')

    # ### end Alembic commands ###
