"""empty message

Revision ID: 741ea421dc9b
Revises: 201151556ae3
Create Date: 2024-10-18 19:32:28.716230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '741ea421dc9b'
down_revision = '201151556ae3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment', sa.String(length=1024), nullable=True))
        batch_op.add_column(sa.Column('algorithm', sa.Integer(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment', sa.String(length=1024), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('comment')

    with op.batch_alter_table('bot_settings', schema=None) as batch_op:
        batch_op.drop_column('algorithm')
        batch_op.drop_column('comment')

    # ### end Alembic commands ###
