"""empty message

Revision ID: 816b1746cf2b
Revises: 4f95c90fbbf2
Create Date: 2024-10-07 19:14:26.048603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '816b1746cf2b'
down_revision = '4f95c90fbbf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('buy')
    op.drop_table('sell')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sell',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('time', sa.DATETIME(), nullable=True),
    sa.Column('amount', sa.FLOAT(), nullable=True),
    sa.Column('price', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('buy',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('time', sa.DATETIME(), nullable=True),
    sa.Column('amount', sa.FLOAT(), nullable=True),
    sa.Column('price', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
