"""empty message

Revision ID: 8501d34c5d83
Revises: c7cf39b1d184
Create Date: 2024-11-17 21:32:52.088810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8501d34c5d83'
down_revision = 'c7cf39b1d184'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('macd_timeperiod', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('macd_signalperiod', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('boilinger_timeperiod', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('boilinger_nbdev', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('stock_k_timeperiod', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('stock_d_timeperiod', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ema_fast_timeperiod', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ema_slow_timeperiod', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot_settings', schema=None) as batch_op:
        batch_op.drop_column('ema_slow_timeperiod')
        batch_op.drop_column('ema_fast_timeperiod')
        batch_op.drop_column('stock_d_timeperiod')
        batch_op.drop_column('stock_k_timeperiod')
        batch_op.drop_column('boilinger_nbdev')
        batch_op.drop_column('boilinger_timeperiod')
        batch_op.drop_column('macd_signalperiod')
        batch_op.drop_column('macd_timeperiod')

    # ### end Alembic commands ###
