"""empty message

Revision ID: 936c4ca07b5b
Revises: 1fffff2be8d2
Create Date: 2024-11-03 19:16:49.157557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '936c4ca07b5b'
down_revision = '1fffff2be8d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('backtest_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('symbol', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('strategy', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('algorithm', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('backtest_results', schema=None) as batch_op:
        batch_op.drop_column('algorithm')
        batch_op.drop_column('strategy')
        batch_op.drop_column('symbol')

    # ### end Alembic commands ###
