"""empty message

Revision ID: a594c3fb817c
Revises: fed9a0cc7684
Create Date: 2024-11-02 19:57:14.023026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a594c3fb817c'
down_revision = 'fed9a0cc7684'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtest_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('interval', sa.String(length=16), nullable=False),
    sa.Column('bot_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.String(length=16), nullable=False),
    sa.Column('end_date', sa.String(length=16), nullable=True),
    sa.Column('csv_file_path', sa.String(length=16), nullable=False),
    sa.Column('initial_balance', sa.Integer(), nullable=False),
    sa.Column('crypto_balance', sa.Integer(), nullable=True),
    sa.Column('strategy', sa.String(length=16), nullable=False),
    sa.Column('algorithm', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('backtest_settings')
    # ### end Alembic commands ###
