"""empty message

Revision ID: a90db4a24faa
Revises: 9080bc5f8799
Create Date: 2024-11-02 21:21:37.848276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a90db4a24faa'
down_revision = '9080bc5f8799'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('backtest_settings', schema=None) as batch_op:
        batch_op.alter_column('end_date',
               existing_type=sa.VARCHAR(length=16),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('backtest_settings', schema=None) as batch_op:
        batch_op.alter_column('end_date',
               existing_type=sa.VARCHAR(length=16),
               nullable=True)

    # ### end Alembic commands ###
