"""empty message

Revision ID: be7a39fbaf52
Revises: 2b26bb8eb8d1
Create Date: 2024-11-03 20:57:17.099451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be7a39fbaf52'
down_revision = '2b26bb8eb8d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot_settings', schema=None) as batch_op:
        batch_op.alter_column('sell_signal_only_trailing_stop',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('atr_trailing_stop',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot_settings', schema=None) as batch_op:
        batch_op.alter_column('atr_trailing_stop',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('sell_signal_only_trailing_stop',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
