"""empty message

Revision ID: ca557cff6b86
Revises: be7a39fbaf52
Create Date: 2024-11-06 21:13:45.536336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca557cff6b86'
down_revision = 'be7a39fbaf52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trailing_stop_with_atr', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('trailing_stop_atr_calc', sa.Float(), nullable=False, server_default='1.5'))
        batch_op.drop_column('atr_trailing_stop')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('atr_trailing_stop', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('trailing_stop_atr_calc')
        batch_op.drop_column('trailing_stop_with_atr')

    # ### end Alembic commands ###
