"""empty message

Revision ID: e55336c4e37f
Revises: 0b888f0d9dd2
Create Date: 2024-10-16 21:40:20.891614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e55336c4e37f'
down_revision = '0b888f0d9dd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot_current_trade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('buy_price', sa.Float(), nullable=True))

    with op.batch_alter_table('trades_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('buy_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('sell_price', sa.Float(), nullable=True))
        batch_op.drop_column('price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trades_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.FLOAT(), nullable=True))
        batch_op.drop_column('sell_price')
        batch_op.drop_column('buy_price')

    with op.batch_alter_table('bot_current_trade', schema=None) as batch_op:
        batch_op.drop_column('buy_price')

    # ### end Alembic commands ###
