"""empty message

Revision ID: e759c6a919c6
Revises: 
Create Date: 2024-09-28 14:11:54.338677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e759c6a919c6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy', sa.String(length=150), nullable=True),
    sa.Column('trading_enabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trade_time', sa.DateTime(), nullable=True),
    sa.Column('buy_or_sell', sa.String(length=10), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=56), nullable=False),
    sa.Column('name', sa.String(length=56), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=False),
    sa.Column('control_panel_access', sa.Boolean(), nullable=False),
    sa.Column('admin_panel_access', sa.Boolean(), nullable=False),
    sa.Column('email_raports_receiver', sa.Boolean(), nullable=False),
    sa.Column('login_errors', sa.Integer(), nullable=False),
    sa.Column('account_suspended', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('login')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('trades')
    op.drop_table('settings')
    # ### end Alembic commands ###
