"""empty message

Revision ID: eacb907c22fa
Revises: 
Create Date: 2024-10-27 17:30:04.666395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eacb907c22fa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=True),
    sa.Column('comment', sa.String(length=1024), nullable=True),
    sa.Column('strategy', sa.String(length=16), nullable=True),
    sa.Column('trailing_stop_pct', sa.Float(), nullable=True),
    sa.Column('cci_buy', sa.Integer(), nullable=True),
    sa.Column('cci_sell', sa.Integer(), nullable=True),
    sa.Column('rsi_buy', sa.Integer(), nullable=True),
    sa.Column('rsi_sell', sa.Integer(), nullable=True),
    sa.Column('mfi_buy', sa.Integer(), nullable=True),
    sa.Column('mfi_sell', sa.Integer(), nullable=True),
    sa.Column('timeperiod', sa.Integer(), nullable=True),
    sa.Column('interval', sa.String(length=16), nullable=True),
    sa.Column('lookback_period', sa.String(length=16), nullable=True),
    sa.Column('signals_extended', sa.Boolean(), nullable=True),
    sa.Column('bot_running', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=56), nullable=False),
    sa.Column('name', sa.String(length=56), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('comment', sa.String(length=1024), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=False),
    sa.Column('control_panel_access', sa.Boolean(), nullable=False),
    sa.Column('admin_panel_access', sa.Boolean(), nullable=False),
    sa.Column('email_raports_receiver', sa.Boolean(), nullable=False),
    sa.Column('login_errors', sa.Integer(), nullable=False),
    sa.Column('account_suspended', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('login')
    )
    op.create_table('bot_current_trade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('buy_price', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('previous_price', sa.Float(), nullable=True),
    sa.Column('trailing_stop_loss', sa.Float(), nullable=True),
    sa.Column('bot_settings_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bot_settings_id'], ['bot_settings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trades_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy', sa.String(length=16), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('buy_price', sa.Float(), nullable=True),
    sa.Column('sell_price', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('bot_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['bot_settings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trades_history')
    op.drop_table('bot_current_trade')
    op.drop_table('users')
    op.drop_table('bot_settings')
    # ### end Alembic commands ###
